name: check markdown

on:
  - pull_request
  - push

jobs:
  check_markdown:
    name: Check Markdown files
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: install modules
        run: yarn

      - name: check markdown files
        run: node test/frontmatter-check.js